### ISSUE TITLE
Feature request: types

### ISSUE THREAD

**Issue by incompletude** [frantz/amazon-s3-uri#7]
Can you provide types?

**Comment by ragilr** [comment]
@frantz i second this

**Comment by frantz** [comment]
Sorry for delay but this project have fallen under my radar... I will add types to package shortly.
I think it would be more maintainable to generate them at build.

**Comment by alfonsoar** [comment]
Hi @frantz - This package is still not generating types. Are you accepting PRs?

**Comment by frantz** [comment]
@alfonsoar @xyleen It could be fixed with `v0.1.1`. PRs are also welcome :)
